### ISSUE TITLE
The arrows arent disapperaing even if show arrow controls is false 

### ISSUE THREAD

**Issue by BSxTitaN** [madzadev/image-slider#1]
`import styled from "styled-components";
import Image from "next/image";
import Slider from "@madzadev/image-slider";
import "@madzadev/image-slider/dist/index.css";

export default function Sliders() {
const images = [{ url: "/1.png" }, { url: "/2.png" }, { url: "/3.png" }];
return (
  <mgSection>
    <div className="sliderr">
      <Slider
        imageList={images}
        height={662}
        width={1247}
        loop={true}
        autoPlay={true}
        autoPlayInterval={5000}
        **showArrowControls={false}**
        showDotControls={false}
      />
    </div>
  </mgSection>
);
}

const ImgSection = styled.section`
`;`

**Comment by madzadev** [comment]
@BSxTitaN Thanks for reporting! I will look into this 😉

**Comment by madzadev** [comment]
@BSxTitaN It should be fixed by now. Had to update to display conditionals on loop.
