### ISSUE TITLE
Module not found: Can't resolve 'image-slider/dist/index.css'

### ISSUE THREAD

**Issue by sharunrajeev** [madzadev/image-slider#2]
I am using nextjs for the project. How to import this file?

**Comment by madzadev** [comment]
@sharunrajeev Thanks for using the image-slider package.
Just tested on my computer using:

```
npx create-next-app image-slider
npm install @madzadev/image-slider --legacy-peer-deps
```

Everything works as expected, make sure to also install the settings for nextjs:
```
npm i next-images next-transpile-modules
```

and use these configs in `next.config.js`:
```
const withImages = require("next-images");
const withTM = require("next-transpile-modules")(["@madzadev/image-slider"]);

module.exports = withImages(withTM());
```

TL;DR the setup process is documented in the [readme](https://github.com/madzadev/image-slider/blob/master/README.md)
